### ISSUE TITLE
[Request] Kibana

### ISSUE THREAD

**Issue by simshaun** [jtreminio/dashtainer#10]
Would be cool if a Kibana service could be added to a project.

For reference, this is the configuration I'm using:
```yaml
services:
    kibana:
        image: 'docker.elastic.co/kibana/kibana-oss:6.2.3'
        depends_on:
            - elasticsearch
        environment:
            SERVER_NAME: 'kibana'
            SERVER_HOST: '0.0.0.0'
            ELASTICSEARCH_URL: 'http://elasticsearch:9200'
        labels:
            - 'traefik.enable=true'
            - 'traefik.backend=kibana'
            - 'traefik.port=5601'
            - 'traefik.docker.network=traefik_webgateway'
            - 'traefik.frontend.rule=Host:kibana.loc,www.kibana.loc'
        networks:
            - shared
            - public
        ports:
            - '5601:5601'
        volumes:
            - './kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:delegated'
```
Stuff to be aware of if using the reference above:
* I use `.loc` instead of `.localhost`
* I've customized Traefik to require traefik.enable. I don't think Dashtainer's default Traefik config needs that.
* `kibana.yml` is empty. I just pre-emptively created it.
* shared & public networks are my own custom networks.
* I'm not really sure if the SERVER_HOST and ELASTICSEARCH_URL environment vars are really necessary.
