### ISSUE TITLE
Add RedisCommander

### ISSUE THREAD

**Issue by jtreminio** [jtreminio/dashtainer#42]
Sample config:

```
version: '3.2'
networks:
  private:
  public:
    external:
      name: traefik_webgateway
volumes:
  redis-datadir:
services:
  redis:
    image: redis:4.0
    networks:
      - private
    volumes:
      - redis-datadir:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:redis:6379
    labels:
      - traefik.backend={$COMPOSE_PROJECT_NAME}_redis
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:redis.app.localhost
      - traefik.port=8081
    networks:
      - private
      - public

```
