### ISSUE TITLE
Secret name and ServiceSecret source should match

### ISSUE THREAD

**Issue by jtreminio** [jtreminio/dashtainer#46]
Secret and source should always match:

```
version: '3.2'
networks:
  private: 
  public:
    external:
      name: traefik_webgateway
secrets:
  redis-redis-host:
    file: ./secrets/redis-redis_host
volumes:
  redis-datadir: 
services:
  redis:
    image: 'redis:4.0'
    networks:
      - private
    secrets:
      -
        source: redis-redis_host
        target: redis_host
        uid: "0"
        gid: "0"
        mode: 0444
    volumes:
      - "redis-datadir:/data"
```
