### ISSUE TITLE
Secret uid, gid, or mode not supported in non-Swarm mode

### ISSUE THREAD

**Issue by jtreminio** [jtreminio/dashtainer#47]
> WARNING: Service "redis" uses secret "redis-redis-host" with uid, gid, or mode. These fields are not supported by this implementation of the Compose file

```
version: '3.2'
networks:
  private: 
  public:
    external:
      name: traefik_webgateway
secrets:
  redis-redis-host:
    file: ./secrets/redis-redis_host
volumes:
  redis-datadir: 
services:
  redis:
    image: 'redis:4.0'
    networks:
      - private
    secrets:
      -
        source: redis-redis_host
        target: redis_host
        uid: "0"
        gid: "0"
        mode: 0444
    volumes:
      - "redis-datadir:/data"
```
